import Header from '@/components/Header/Header'


import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/Footer'
import { CartProvider } from '@/Providers/CartProvider/CartProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: {title:string, description: string}= {
  title: 'CREOATE - Wholesale Marketplace for Independent Brands',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
          crossOrigin="anonymous"
        />
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"/>
      </head>
      <body className={inter.className}>
      <CartProvider>
        <Header/>
        {children}
      </CartProvider>
      <Footer/>
      </body>
    </html>

  )
}


